import { type PokeType } from "@hinagata-next/core/feature/pokemon-sv-types";

export type SvPokemon = {
  name: string;
  types: PokeType[];
  // PokeAPIのポケモンID（フォルム違いは10000番台の専用ID）
  imageId: number;
};

// 公式アートワーク画像のURL（PokeAPI sprites リポジトリのミラーを参照）
export const pokemonArtworkUrl = (p: SvPokemon) =>
  `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${p.imageId}.png`;

// SVランクバトルでよく見かけるポケモンの抜粋
export const SV_POKEDEX: SvPokemon[] = [
  { name: "カイリュー", types: ["dragon", "flying"], imageId: 149 },
  { name: "ガブリアス", types: ["dragon", "ground"], imageId: 445 },
  { name: "ボーマンダ", types: ["dragon", "flying"], imageId: 373 },
  { name: "サザンドラ", types: ["dark", "dragon"], imageId: 635 },
  { name: "ドラパルト", types: ["dragon", "ghost"], imageId: 887 },
  { name: "セグレイブ", types: ["dragon", "ice"], imageId: 998 },
  { name: "ブリジュラス", types: ["steel", "dragon"], imageId: 1018 },
  { name: "キングドラ", types: ["water", "dragon"], imageId: 230 },
  { name: "シャリタツ", types: ["dragon", "water"], imageId: 978 },
  { name: "カミッチュ", types: ["grass", "dragon"], imageId: 1011 },
  { name: "ハバタクカミ", types: ["ghost", "fairy"], imageId: 987 },
  { name: "テツノツツミ", types: ["ice", "water"], imageId: 991 },
  { name: "テツノブジン", types: ["fairy", "fighting"], imageId: 1006 },
  { name: "テツノドクガ", types: ["fire", "poison"], imageId: 994 },
  { name: "テツノカイナ", types: ["fighting", "electric"], imageId: 992 },
  { name: "テツノワダチ", types: ["ground", "steel"], imageId: 990 },
  { name: "テツノコウベ", types: ["dark", "flying"], imageId: 993 },
  { name: "テツノイバラ", types: ["rock", "electric"], imageId: 995 },
  { name: "テツノカシラ", types: ["steel", "psychic"], imageId: 1023 },
  { name: "テツノイワオ", types: ["rock", "psychic"], imageId: 1022 },
  { name: "トドロクツキ", types: ["dragon", "dark"], imageId: 1005 },
  { name: "アラブルタケ", types: ["grass", "poison"], imageId: 986 },
  { name: "スナノケガワ", types: ["electric", "ground"], imageId: 989 },
  { name: "イダイナキバ", types: ["ground", "fighting"], imageId: 984 },
  { name: "サケブシッポ", types: ["fairy", "psychic"], imageId: 985 },
  { name: "チヲハウハネ", types: ["bug", "fighting"], imageId: 988 },
  { name: "ウネルミナモ", types: ["water", "dragon"], imageId: 1009 },
  { name: "タケルライコ", types: ["electric", "dragon"], imageId: 1021 },
  { name: "ウガツホムラ", types: ["fire", "dragon"], imageId: 1020 },
  { name: "パオジアン", types: ["dark", "ice"], imageId: 1002 },
  { name: "ディンルー", types: ["dark", "ground"], imageId: 1003 },
  { name: "イーユイ", types: ["dark", "fire"], imageId: 1004 },
  { name: "チオンジェン", types: ["dark", "grass"], imageId: 1001 },
  { name: "サーフゴー", types: ["steel", "ghost"], imageId: 1000 },
  { name: "ガチグマ(アカツキ)", types: ["ground", "normal"], imageId: 10272 },
  { name: "ウーラオス(いちげき)", types: ["fighting", "dark"], imageId: 892 },
  {
    name: "ウーラオス(れんげき)",
    types: ["fighting", "water"],
    imageId: 10191
  },
  {
    name: "ランドロス(れいじゅう)",
    types: ["ground", "flying"],
    imageId: 10021
  },
  { name: "オーガポン", types: ["grass"], imageId: 1017 },
  { name: "オーガポン(かまど)", types: ["grass", "fire"], imageId: 10274 },
  { name: "オーガポン(いど)", types: ["grass", "water"], imageId: 10273 },
  { name: "オーガポン(いしずえ)", types: ["grass", "rock"], imageId: 10275 },
  { name: "ヒードラン", types: ["fire", "steel"], imageId: 485 },
  { name: "クレセリア", types: ["psychic"], imageId: 488 },
  { name: "サンダー", types: ["electric", "flying"], imageId: 145 },
  { name: "ミミッキュ", types: ["ghost", "fairy"], imageId: 778 },
  { name: "キョジオーン", types: ["rock"], imageId: 934 },
  { name: "ヘイラッシャ", types: ["water"], imageId: 977 },
  { name: "ドオー", types: ["poison", "ground"], imageId: 980 },
  { name: "キラフロル", types: ["rock", "poison"], imageId: 970 },
  { name: "デカヌチャン", types: ["fairy", "steel"], imageId: 959 },
  { name: "マスカーニャ", types: ["grass", "dark"], imageId: 908 },
  { name: "ラウドボーン", types: ["fire", "ghost"], imageId: 911 },
  { name: "ウェーニバル", types: ["water", "fighting"], imageId: 914 },
  { name: "ソウブレイズ", types: ["fire", "ghost"], imageId: 937 },
  { name: "グレンアルマ", types: ["fire", "psychic"], imageId: 936 },
  { name: "ドドゲザン", types: ["dark", "steel"], imageId: 983 },
  { name: "コノヨザル", types: ["fighting", "ghost"], imageId: 979 },
  { name: "イルカマン", types: ["water"], imageId: 964 },
  { name: "ブロロローム", types: ["steel", "poison"], imageId: 966 },
  { name: "クエスパトラ", types: ["psychic"], imageId: 956 },
  { name: "カラミンゴ", types: ["flying", "fighting"], imageId: 973 },
  { name: "ハラバリー", types: ["electric"], imageId: 939 },
  { name: "ミミズズ", types: ["steel"], imageId: 968 },
  { name: "ガケガニ", types: ["rock"], imageId: 950 },
  { name: "オリーヴァ", types: ["grass", "normal"], imageId: 930 },
  { name: "ノココッチ", types: ["normal"], imageId: 982 },
  { name: "リククラゲ", types: ["ground", "grass"], imageId: 949 },
  { name: "ヤバソチャ", types: ["grass", "ghost"], imageId: 1013 },
  { name: "バンギラス", types: ["rock", "dark"], imageId: 248 },
  { name: "メタグロス", types: ["steel", "psychic"], imageId: 376 },
  { name: "ハッサム", types: ["bug", "steel"], imageId: 212 },
  { name: "ウルガモス", types: ["bug", "fire"], imageId: 637 },
  { name: "アーマーガア", types: ["flying", "steel"], imageId: 823 },
  { name: "ナットレイ", types: ["grass", "steel"], imageId: 598 },
  { name: "ドリュウズ", types: ["ground", "steel"], imageId: 530 },
  { name: "ジバコイル", types: ["electric", "steel"], imageId: 462 },
  { name: "エンペルト", types: ["water", "steel"], imageId: 395 },
  { name: "トゲキッス", types: ["fairy", "flying"], imageId: 468 },
  { name: "サーナイト", types: ["psychic", "fairy"], imageId: 282 },
  { name: "エルレイド", types: ["psychic", "fighting"], imageId: 475 },
  { name: "ニンフィア", types: ["fairy"], imageId: 700 },
  { name: "ブラッキー", types: ["dark"], imageId: 197 },
  { name: "エーフィ", types: ["psychic"], imageId: 196 },
  { name: "グライオン", types: ["ground", "flying"], imageId: 472 },
  { name: "カバルドン", types: ["ground"], imageId: 450 },
  { name: "マンムー", types: ["ice", "ground"], imageId: 473 },
  { name: "パルシェン", types: ["water", "ice"], imageId: 91 },
  { name: "ラプラス", types: ["water", "ice"], imageId: 131 },
  { name: "ギャラドス", types: ["water", "flying"], imageId: 130 },
  { name: "ペリッパー", types: ["water", "flying"], imageId: 279 },
  { name: "ルンパッパ", types: ["water", "grass"], imageId: 272 },
  { name: "トリトドン", types: ["water", "ground"], imageId: 423 },
  { name: "ドヒドイデ", types: ["poison", "water"], imageId: 748 },
  { name: "ブルンゲル", types: ["water", "ghost"], imageId: 593 },
  { name: "マリルリ", types: ["water", "fairy"], imageId: 184 },
  { name: "アシレーヌ", types: ["water", "fairy"], imageId: 730 },
  { name: "ゲッコウガ", types: ["water", "dark"], imageId: 658 },
  { name: "ガオガエン", types: ["fire", "dark"], imageId: 727 },
  { name: "ウインディ", types: ["fire"], imageId: 59 },
  { name: "リザードン", types: ["fire", "flying"], imageId: 6 },
  { name: "ロトム(ウォッシュ)", types: ["electric", "water"], imageId: 10009 },
  { name: "ロトム(ヒート)", types: ["electric", "fire"], imageId: 10008 },
  { name: "モロバレル", types: ["grass", "poison"], imageId: 591 },
  { name: "キノガッサ", types: ["grass", "fighting"], imageId: 286 },
  { name: "ゲンガー", types: ["ghost", "poison"], imageId: 94 },
  { name: "ヨノワール", types: ["ghost"], imageId: 477 },
  { name: "オーロンゲ", types: ["dark", "fairy"], imageId: 861 },
  { name: "クレッフィ", types: ["steel", "fairy"], imageId: 707 },
  { name: "ピクシー", types: ["fairy"], imageId: 36 },
  { name: "カイリキー", types: ["fighting"], imageId: 68 },
  { name: "ローブシン", types: ["fighting"], imageId: 534 },
  { name: "オオニューラ", types: ["fighting", "poison"], imageId: 903 },
  { name: "ポリゴン2", types: ["normal"], imageId: 233 },
  { name: "カビゴン", types: ["normal"], imageId: 143 },
  { name: "ハピナス", types: ["normal"], imageId: 242 },
  { name: "ミロカロス", types: ["water"], imageId: 350 },
  { name: "ランターン", types: ["water", "electric"], imageId: 171 }
];
