import { type PokeType } from "@hinagata-next/core/feature/pokemon-sv-types";

export type SvPokemon = {
  name: string;
  types: PokeType[];
};

// SVランクバトルでよく見かけるポケモンの抜粋
export const SV_POKEDEX: SvPokemon[] = [
  { name: "カイリュー", types: ["dragon", "flying"] },
  { name: "ガブリアス", types: ["dragon", "ground"] },
  { name: "ボーマンダ", types: ["dragon", "flying"] },
  { name: "サザンドラ", types: ["dark", "dragon"] },
  { name: "ドラパルト", types: ["dragon", "ghost"] },
  { name: "セグレイブ", types: ["dragon", "ice"] },
  { name: "ブリジュラス", types: ["steel", "dragon"] },
  { name: "キングドラ", types: ["water", "dragon"] },
  { name: "シャリタツ", types: ["dragon", "water"] },
  { name: "カミッチュ", types: ["grass", "dragon"] },
  { name: "ハバタクカミ", types: ["ghost", "fairy"] },
  { name: "テツノツツミ", types: ["ice", "water"] },
  { name: "テツノブジン", types: ["fairy", "fighting"] },
  { name: "テツノドクガ", types: ["fire", "poison"] },
  { name: "テツノカイナ", types: ["fighting", "electric"] },
  { name: "テツノワダチ", types: ["ground", "steel"] },
  { name: "テツノコウベ", types: ["dark", "flying"] },
  { name: "テツノイバラ", types: ["rock", "electric"] },
  { name: "テツノカシラ", types: ["steel", "psychic"] },
  { name: "テツノイワオ", types: ["rock", "psychic"] },
  { name: "トドロクツキ", types: ["dragon", "dark"] },
  { name: "アラブルタケ", types: ["grass", "poison"] },
  { name: "スナノケガワ", types: ["electric", "ground"] },
  { name: "イダイナキバ", types: ["ground", "fighting"] },
  { name: "サケブシッポ", types: ["fairy", "psychic"] },
  { name: "チヲハウハネ", types: ["bug", "fighting"] },
  { name: "ウネルミナモ", types: ["water", "dragon"] },
  { name: "タケルライコ", types: ["electric", "dragon"] },
  { name: "ウガツホムラ", types: ["fire", "dragon"] },
  { name: "パオジアン", types: ["dark", "ice"] },
  { name: "ディンルー", types: ["dark", "ground"] },
  { name: "イーユイ", types: ["dark", "fire"] },
  { name: "チオンジェン", types: ["dark", "grass"] },
  { name: "サーフゴー", types: ["steel", "ghost"] },
  { name: "ガチグマ(アカツキ)", types: ["ground", "normal"] },
  { name: "ウーラオス(いちげき)", types: ["fighting", "dark"] },
  { name: "ウーラオス(れんげき)", types: ["fighting", "water"] },
  { name: "ランドロス(れいじゅう)", types: ["ground", "flying"] },
  { name: "オーガポン", types: ["grass"] },
  { name: "オーガポン(かまど)", types: ["grass", "fire"] },
  { name: "オーガポン(いど)", types: ["grass", "water"] },
  { name: "オーガポン(いしずえ)", types: ["grass", "rock"] },
  { name: "ヒードラン", types: ["fire", "steel"] },
  { name: "クレセリア", types: ["psychic"] },
  { name: "サンダー", types: ["electric", "flying"] },
  { name: "ミミッキュ", types: ["ghost", "fairy"] },
  { name: "キョジオーン", types: ["rock"] },
  { name: "ヘイラッシャ", types: ["water"] },
  { name: "ドオー", types: ["poison", "ground"] },
  { name: "キラフロル", types: ["rock", "poison"] },
  { name: "デカヌチャン", types: ["fairy", "steel"] },
  { name: "マスカーニャ", types: ["grass", "dark"] },
  { name: "ラウドボーン", types: ["fire", "ghost"] },
  { name: "ウェーニバル", types: ["water", "fighting"] },
  { name: "ソウブレイズ", types: ["fire", "ghost"] },
  { name: "グレンアルマ", types: ["fire", "psychic"] },
  { name: "ドドゲザン", types: ["dark", "steel"] },
  { name: "コノヨザル", types: ["fighting", "ghost"] },
  { name: "イルカマン", types: ["water"] },
  { name: "ブロロローム", types: ["steel", "poison"] },
  { name: "クエスパトラ", types: ["psychic"] },
  { name: "カラミンゴ", types: ["flying", "fighting"] },
  { name: "ハラバリー", types: ["electric"] },
  { name: "ミミズズ", types: ["steel"] },
  { name: "ガケガニ", types: ["rock"] },
  { name: "オリーヴァ", types: ["grass", "normal"] },
  { name: "ノココッチ", types: ["normal"] },
  { name: "リククラゲ", types: ["ground", "grass"] },
  { name: "ヤバソチャ", types: ["grass", "ghost"] },
  { name: "バンギラス", types: ["rock", "dark"] },
  { name: "メタグロス", types: ["steel", "psychic"] },
  { name: "ハッサム", types: ["bug", "steel"] },
  { name: "ウルガモス", types: ["bug", "fire"] },
  { name: "アーマーガア", types: ["flying", "steel"] },
  { name: "ナットレイ", types: ["grass", "steel"] },
  { name: "ドリュウズ", types: ["ground", "steel"] },
  { name: "ジバコイル", types: ["electric", "steel"] },
  { name: "エンペルト", types: ["water", "steel"] },
  { name: "トゲキッス", types: ["fairy", "flying"] },
  { name: "サーナイト", types: ["psychic", "fairy"] },
  { name: "エルレイド", types: ["psychic", "fighting"] },
  { name: "ニンフィア", types: ["fairy"] },
  { name: "ブラッキー", types: ["dark"] },
  { name: "エーフィ", types: ["psychic"] },
  { name: "グライオン", types: ["ground", "flying"] },
  { name: "カバルドン", types: ["ground"] },
  { name: "マンムー", types: ["ice", "ground"] },
  { name: "パルシェン", types: ["water", "ice"] },
  { name: "ラプラス", types: ["water", "ice"] },
  { name: "ギャラドス", types: ["water", "flying"] },
  { name: "ペリッパー", types: ["water", "flying"] },
  { name: "ルンパッパ", types: ["water", "grass"] },
  { name: "トリトドン", types: ["water", "ground"] },
  { name: "ドヒドイデ", types: ["poison", "water"] },
  { name: "ブルンゲル", types: ["water", "ghost"] },
  { name: "マリルリ", types: ["water", "fairy"] },
  { name: "アシレーヌ", types: ["water", "fairy"] },
  { name: "ゲッコウガ", types: ["water", "dark"] },
  { name: "ガオガエン", types: ["fire", "dark"] },
  { name: "ウインディ", types: ["fire"] },
  { name: "リザードン", types: ["fire", "flying"] },
  { name: "ロトム(ウォッシュ)", types: ["electric", "water"] },
  { name: "ロトム(ヒート)", types: ["electric", "fire"] },
  { name: "モロバレル", types: ["grass", "poison"] },
  { name: "キノガッサ", types: ["grass", "fighting"] },
  { name: "ゲンガー", types: ["ghost", "poison"] },
  { name: "ヨノワール", types: ["ghost"] },
  { name: "オーロンゲ", types: ["dark", "fairy"] },
  { name: "クレッフィ", types: ["steel", "fairy"] },
  { name: "ピクシー", types: ["fairy"] },
  { name: "カイリキー", types: ["fighting"] },
  { name: "ローブシン", types: ["fighting"] },
  { name: "オオニューラ", types: ["fighting", "poison"] },
  { name: "ポリゴン2", types: ["normal"] },
  { name: "カビゴン", types: ["normal"] },
  { name: "ハピナス", types: ["normal"] },
  { name: "ミロカロス", types: ["water"] },
  { name: "ランターン", types: ["water", "electric"] }
];
