export type HeritageSite = {
  nameJa: string;
  nameEn: string;
  startSec: number;
};

export const HERITAGE_SITES: HeritageSite[] = [
  { nameJa: "アマルフィ海岸", nameEn: "Amalfi", startSec: 49 },
  { nameJa: "ブラーノ島", nameEn: "Burano", startSec: 111 },
  { nameJa: "シヨン城", nameEn: "Chillon Castle", startSec: 150 },
  { nameJa: "テカポ湖", nameEn: "Lake Tekapo", startSec: 196 },
  { nameJa: "サントリーニ島", nameEn: "Santorini Island", startSec: 236 },
  { nameJa: "ウユニ塩湖", nameEn: "Uyuni Salt Lake", startSec: 301 },
  { nameJa: "シギリヤロック", nameEn: "Sigiriya Rock", startSec: 361 },
  { nameJa: "バオバブ並木", nameEn: "Avenue of the Baobabs", startSec: 415 },
  { nameJa: "十字架の丘", nameEn: "Hill of Crosses", startSec: 457 },
  { nameJa: "ハルシュタット", nameEn: "Hallstatt", startSec: 505 },
  { nameJa: "カッパドキア", nameEn: "Cappadocia", startSec: 550 },
  { nameJa: "イエローストーン", nameEn: "Yellowstone National Park", startSec: 606 },
  { nameJa: "ドゥブロヴニク", nameEn: "Dubrovnik", startSec: 664 },
  { nameJa: "ナヴァイオビーチ", nameEn: "Navagio Beach", startSec: 714 },
  { nameJa: "エアーズロック", nameEn: "Ayers Rock", startSec: 758 },
  { nameJa: "ワイトモ洞窟", nameEn: "Waitomo Caves", startSec: 815 },
  { nameJa: "マリーナベイサンズ", nameEn: "Marina Bay Sands", startSec: 858 },
  { nameJa: "サグラダ・ファミリア", nameEn: "Sagrada Família", startSec: 902 },
  { nameJa: "ロンダ", nameEn: "Ronda", startSec: 968 },
  { nameJa: "コムローイ", nameEn: "Khom Loi", startSec: 1035 },
  { nameJa: "チョコレート・ヒルズ", nameEn: "Chocolate Hills", startSec: 1092 },
  { nameJa: "ノイシュヴァンシュタイン城", nameEn: "Neuschwanstein Castle", startSec: 1129 },
  { nameJa: "アヤソフィア", nameEn: "Hagia Sophia", startSec: 1280 },
  { nameJa: "アルバラシン", nameEn: "Albarracín", startSec: 1319 },
  { nameJa: "ドバイ・フレーム", nameEn: "Dubai Frame", startSec: 1385 },
  { nameJa: "万里の長城", nameEn: "The Great Wall of China", startSec: 1431 },
  { nameJa: "アゲダ", nameEn: "Águeda", startSec: 1488 },
  { nameJa: "アンコール・トム", nameEn: "Angkor Thom", startSec: 1539 },
  { nameJa: "アルベロベッロのトゥルッリ", nameEn: "Trulli di Alberobello", startSec: 1572 },
  { nameJa: "グラナダ", nameEn: "Granada", startSec: 1644 },
  { nameJa: "メテオラ", nameEn: "Meteora", startSec: 1692 },
  { nameJa: "モニュメントバレー", nameEn: "Monument Valley", startSec: 1748 },
  { nameJa: "グアナファト", nameEn: "Guanajuato", startSec: 1797 },
  { nameJa: "メープル街道", nameEn: "Maple Road", startSec: 1862 },
  { nameJa: "エンジェルフォール", nameEn: "Angel Falls", startSec: 1915 },
  { nameJa: "九塞溝", nameEn: "Jiuzhaigou", startSec: 1973 },
  { nameJa: "ペリトモレノ大氷河", nameEn: "Glaciar Perito Moreno", startSec: 2037 },
  { nameJa: "ジャイプール", nameEn: "Jaipur", startSec: 2096 },
  { nameJa: "サハラ砂漠", nameEn: "Sahara Desert", startSec: 2193 },
  { nameJa: "クロンボー城", nameEn: "Kronborg Castle", startSec: 2236 },
  { nameJa: "ブルジュハリファ", nameEn: "Burj Khalifa", startSec: 2262 },
  { nameJa: "紫禁城", nameEn: "Forbidden City", startSec: 2333 },
  { nameJa: "ストックホルム", nameEn: "Stockholm", startSec: 2371 },
  { nameJa: "ラチャダー鉄道市場", nameEn: "Talat Rotfai Ratchada", startSec: 2418 },
  { nameJa: "ギザのピラミッド", nameEn: "Pyramids of Giza", startSec: 2462 },
  { nameJa: "ベルニナ・エクスプレス", nameEn: "Bernina Express", startSec: 2504 },
  { nameJa: "シャンボール城", nameEn: "Chambord", startSec: 2558 },
  { nameJa: "トレド", nameEn: "Toledo", startSec: 2609 },
  { nameJa: "チンクエ・テッレ", nameEn: "Cinque Terre", startSec: 2679 },
  { nameJa: "フリヒリアナ", nameEn: "Frigiliana", startSec: 2738 },
  { nameJa: "エズ", nameEn: "Eze", startSec: 2779 },
  { nameJa: "チャンギ空港", nameEn: "Changi Airport", startSec: 2828 },
  { nameJa: "パムッカレ", nameEn: "Pamukkale", startSec: 2881 },
  { nameJa: "レンソイス・マラニャンセス国立公園", nameEn: "Lencois Maranhenses National Park", startSec: 2938 },
  { nameJa: "ミコノス島", nameEn: "Mykonos Island", startSec: 2980 },
  { nameJa: "コルチュラ島", nameEn: "Korcula Island", startSec: 3037 },
  { nameJa: "プラハ城", nameEn: "Prague Castle", startSec: 3088 },
  { nameJa: "コルマール", nameEn: "Colmar", startSec: 3146 },
  { nameJa: "シンガポール・フライヤー", nameEn: "Singapore Flyer", startSec: 3200 },
  { nameJa: "エディンバラ", nameEn: "Edinburgh", startSec: 3254 },
  { nameJa: "フヴァル島", nameEn: "Hvar Island", startSec: 3300 },
  { nameJa: "グランドキャニオン", nameEn: "Grand Canyon", startSec: 3351 },
  { nameJa: "テオティワカン", nameEn: "Teotihuacan", startSec: 3409 },
  { nameJa: "イエローナイフ", nameEn: "Yellowknife", startSec: 3461 },
  { nameJa: "フスカル", nameEn: "Juzcar", startSec: 3516 },
  { nameJa: "クエンカ", nameEn: "Cuenca", startSec: 3579 },
  { nameJa: "セブンマイルブリッジ", nameEn: "Seven Mile Bridge", startSec: 3644 },
  { nameJa: "サルベーションマウンテン", nameEn: "Salvation Mountain", startSec: 3695 },
  { nameJa: "モレーン湖", nameEn: "Moraine Lake", startSec: 3749 },
  { nameJa: "マチュピチュ", nameEn: "Machu Picchu", startSec: 3803 },
  { nameJa: "ヴィレムスタット歴史地区", nameEn: "Willemstad", startSec: 3872 },
  { nameJa: "ジョードプル", nameEn: "Jodhpur", startSec: 3929 },
  { nameJa: "アンコールワット", nameEn: "Angkor Wat", startSec: 3975 },
  { nameJa: "シティブサイド", nameEn: "Sidi Bou Said", startSec: 4028 },
  { nameJa: "ポタラ宮", nameEn: "Potala Palace", startSec: 4080 },
  { nameJa: "コペンハーゲン", nameEn: "Copenhagen", startSec: 4188 },
  { nameJa: "ツェルマット", nameEn: "Zermatt", startSec: 4240 },
  { nameJa: "ザ・パール", nameEn: "The Pearl", startSec: 4285 },
  { nameJa: "オスロブ", nameEn: "Oslob", startSec: 4332 },
  { nameJa: "モンスターマンション", nameEn: "Yick Fat Building (Monster Mansion)", startSec: 4382 },
  { nameJa: "シチリア島", nameEn: "Sicily", startSec: 4433 },
  { nameJa: "シャウエン", nameEn: "Chefchaouen", startSec: 4490 },
  { nameJa: "九份", nameEn: "Jiufen", startSec: 4594 },
  { nameJa: "ジャイサルメール", nameEn: "Jaisalmer", startSec: 4646 },
  { nameJa: "ナイアガラの滝", nameEn: "Niagara Falls", startSec: 4701 },
  { nameJa: "アンテロープキャニオン", nameEn: "Antelope Canyon", startSec: 4755 },
  { nameJa: "レドニツェ城", nameEn: "Lednice Chateau", startSec: 4806 },
  { nameJa: "ガーデンズバイザベイ", nameEn: "Gardens by the Bay", startSec: 4868 },
  { nameJa: "スルタンアフメット・ジャミィ", nameEn: "Blue Mosque", startSec: 4921 },
  { nameJa: "チェスキークルムロフ", nameEn: "Cesky Krumlov", startSec: 4976 },
  { nameJa: "クレタ島", nameEn: "Crete Island", startSec: 5025 },
  { nameJa: "マラスの塩田", nameEn: "Salt Mines of Maras", startSec: 5071 },
  { nameJa: "キンデルダイク", nameEn: "Kinderdijk", startSec: 5133 },
  { nameJa: "ポルト", nameEn: "Porto", startSec: 5180 },
  { nameJa: "モトブン", nameEn: "Motovun", startSec: 5225 }
];
