name: build and deploy firebase hosting

on:
  push:
    branches:
      - sample

env:
  ACTIONS_INSTALL_COMMAND: pnpm install
  ACTIONS_BUILD_COMMAND: pnpm run build
  ACTIONS_BUILD_DIST: dist
  ACTIONS_LOCK_FILE: pnpm-lock.yaml

  NEXT_PUBLIC_SITE_ORIGIN: https://example.com

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - uses: pnpm/action-setup@v4

      - uses: google-github-actions/auth@v2
        id: auth
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles(format('**/{0}',env.ACTIONS_LOCK_FILE)) }}
          restore-keys: ${{ runner.os }}-node-

      - name: install dependencies
        run: ${{ env.ACTIONS_INSTALL_COMMAND }}

      - name: build
        run: ${{ env.ACTIONS_BUILD_COMMAND }}

      - name: firebase deploy
        env:
          GOOGLE_OAUTH_ACCESS_TOKEN: ${{ steps.auth.outputs.access_token }}
        run: pnpm exec firebase deploy --only hosting
