name: build and deploy s3

on:
  push:
    branches:
      - sample

env:
  ACTIONS_INSTALL_COMMAND: pnpm install
  ACTIONS_BUILD_COMMAND: pnpm run build
  ACTIONS_BUILD_DIST: dist
  ACTIONS_LOCK_FILE: pnpm-lock.yaml

  NEXT_PUBLIC_SITE_ORIGIN: https://example.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - uses: pnpm/action-setup@v4

      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles(format('**/{0}',env.ACTIONS_LOCK_FILE)) }}
          restore-keys: ${{ runner.os }}-node-

      - name: install dependencies
        run: ${{ env.ACTIONS_INSTALL_COMMAND }}

      - name: build
        run: ${{ env.ACTIONS_BUILD_COMMAND }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: aws sync
        env:
          SYNC_FROM: ${{ env.ACTIONS_BUILD_DIST }}${{ env.NEXT_PUBLIC_BASE_PATH }}/
          SYNC_TO: s3://sample-s3-bucket
        run: aws s3 sync ${SYNC_FROM} ${SYNC_TO} --exact-timestamps --exclude "**/.*" --cache-control max-age=60 --delete
